#!/bin/bash

case "$1" in
  install)
    echo "DevBox sudah terinstall"
    ;;
  backup)
    git add .
    git commit -m "backup $(date)"
    git push origin main
    ;;
  deploy)
    git add .
    git commit -m "deploy update"
    git push origin main
    ;;
  update)
    cd $HOME/devbox-cli && git pull origin main
    ;;
  *)
    echo "DevBox CLI"
    echo "backup | deploy | update"
    ;;
esac
